# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: libations_development
  pool:     5
  username: libation
  password: libation
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: libations_test
  pool:     5
  username: libation
  password: libation
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: libations_production
  pool:     5
  username: libation
  password: libation
  template: template0
